### PR TITLE
Use correct media upload

### PR DESCRIPTION
**Pull request by TerjeBr**

### CODE REVIEW

**Comment by araines** [comment]
I don't know why we need this.  I just did a simple test with the untouched version of the library and successfully uploaded an image with my status update as per the documentation.

Docs here: https://twitteroauth.com/

Script I used:
```
$connection = new TwitterOAuth($key, $sec, $oToken, $oSecret);
$connection->setTimeouts(15, 15);
$content = $connection->get('account/verify_credentials');

$media = $connection->upload('media/upload', array('media' => 'data/twitter-test-images/test1.jpg'));

$params = array(
    'status' => 'Testing testing!',
    'media_ids' => implode(',', array($media->media_id_string)),
);

$result = $connection->post('statuses/update', $params);
```

**Comment by TerjeBr** [comment]
You are the one that insisted that we comply with the Twitter documentation on their website, and not use f.ex. deprecated calls. I took it to mean that we should not rely on undocumented features as well.

That `media/upload` currently accepts normal POSTS that is not `multipart/form-data` is an undocumented feature that we should not rely on.

**Comment by araines** [comment]
OK - I wasn't really expecting anyone to pull the library apart to see if it does what it should :)  So I guess it functionally works at the moment, which means we should be able to leave this for now (as a lower priority change) and get our API code out on the stock version of the library?

Given we've spotted this (and its not urgent) lets get it submitted back as a PR to the main library and get our API code out on the stock version of the library.  When they accept the change, we will pick it up through composer updates.

This means we don't have to faff around with switching back to the core library in future (we do it automatically through updates) and we can get the fix out now.

**Comment by araines** [comment]
OK as discussed, given our tests are already expecting this, lets use our version for now, but we must consider getting back to on the stock library asap.  Also lets get it submitted to the stock library.

**Pull request merged**
